name: Publish to Dockerhub

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag name without 'v' prefix
        id: tag_name
        run: echo "TAG_NAME=$(echo '${GITHUB_REF#refs/tags/v}')"
        shell: bash
        continue-on-error: false

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.tag_name.outputs.TAG_NAME }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-image:${{ steps.tag_name.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/my-image:latest
  update-argocd:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update ArgoCD project file with latest tag
        run: |
          TAG=${{ github.ref }}
          TAG_NAME=$(echo "$TAG" | sed 's/refs\/tags\///')  # Get the actual tag name (remove refs/tags/)

          # Change the value in the values file
          sed -i "s/tag:.*/tag: ${TAG_NAME}/" mizika-bot/k8s/mizika-bot.values

          # Commit and push the change
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add mizika-bot/k8s/mizika-bot.values
          git commit -m "Update tag to ${TAG_NAME}"
          git push origin HEAD:main  # Push to your desired branch
